TYPES = [
        "NONE",
        "OBJ_DIR",
        "OBJ_ARR",
        "NVLIST",
        "NVLIST_SIZE",
        "BPLIST",
        "BPLIST_HDR",
        "SPACE_MAP_HEADER",
        "SPACE_MAP",
        "ILOG",
        "DNODE",
        "OBJSET",
        "DSL_DATASET",
        "DSL_DATASET_CHILD_MAP",
        "OBJSET_SNAP_MAP",
        "DSL_PROPS",
        "DSL_OBJSET",
        "ZNODE",
        "ACL",
        "FILE_CONTENT",
        "DIR_CONTENT",
        "MASTER_NODE",
        "DELETE_QUEUE",
        "ZVOL",
        "ZVOL_PROP"
]
TYPES += [None] * (256 - len(TYPES))
TYPES[196] = "ZAP_METADATA"

CKFUNC = [
        "INHERIT",
        "ON",
        "OFF",
        "LABEL",
        "GANG_HEADER",
        "ZILOG",
        "FLETCHER2",
        "FLETCHER4",
        "SHA-256",
        "ZILOG2",
        "NOPARITY",
        "SHA-512",
        "SKEIN",
        "EDONR",
]

COMP = [
        "INHERIT",
        "LZJB",
        "NONE",
        "LZJB",
        "EMPTY",
        "GZ-1",
        "GZ-2",
        "GZ-3",
        "GZ-4",
        "GZ-5",
        "GZ-6",
        "GZ-7",
        "GZ-8",
        "GZ-9",
        "ZLE",
        "LZ4",
]

